### ISSUE TITLE
Feil konvertering av nordsamisk bokstaver i korpus (Bugzilla Bug 1954)

### ISSUE THREAD

**Issue by albbas** [giellalt/CorpusTools#203]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 1954
Date: 2015-01-15T13:29:07+01:00
From: @leneantonsen (Originally created by @leneantonsen)
To:   @albbas
CC:   ailu.west.92, @ciprian-NO, @snomos, @Trondtr

Last updated: 2016-09-30T00:43:23+02:00

**Comment by albbas** [comment]
## Comment 9983
Date: 2015-01-15 13:29:07 +0100
From: @leneantonsen

Feil konvertering av nordsamisk bokstaver i science-korpus:

đ > ÿ
č > þ
ŋ > ƾ


 i dette dokumentet:

boundcorpus/converted/sme/science/allaskuvla/publications/diedut/Diedut_2007_3_bokblokka.pdf.xml

**Comment by albbas** [comment]
## Comment 10033
Date: 2015-01-29 11:54:37 +0100
From: @Trondtr

Eg konverterer no science-korpus på gtlab, og får eit anna resultat enn Lene. Mitt resultat er at __samtlege__ filer i science får denne beskjeden:

Could not convert orig/sme/science/allaskuvla/publications/diedut/diedut_2007_3_bokblokka.pdf

Heller enn at samtlege forskarar har lagra pdf-filene sine feil ser det ut for meg til at feilen må vere ein annan stad.

Og i loggen står det:

<string>:0:0:ERROR:XSLT:ERR_OK: Variable 'multilingual' has not been declared.

Det er rett nok det, i xsl-templatet er det ingen slik variabel.

Ergo tenkjer eg: her har vi versjonskrasj mellom ulike xsl-filer

Så slettar eg xsl-fila, konverterer på nytt, fyller ut variablane, og får denne meldinga:

Fill in meta info in diedut_2007_3_bokblokka.pdf.xsl , then run this command again
diedut>em diedut_2007_3_bokblokka.pdf.xsl 
diedut>convert2xml diedut_2007_3_bokblokka.pdf
Traceback (most recent call last):
  File "/usr/bin/convert2xml", line 9, in <module>
    load_entry_point('CorpusTools==0.7.8', 'console_scripts', 'convert2xml')()
  File "/usr/lib/python2.7/site-packages/CorpusTools-0.7.8-py2.7.egg/corpustools/converter.py", line 1837, in main
    worker(xsl_file)
  File "/usr/lib/python2.7/site-packages/CorpusTools-0.7.8-py2.7.egg/corpustools/converter.py", line 1787, in worker
    conv.write_complete()
  File "/usr/lib/python2.7/site-packages/CorpusTools-0.7.8-py2.7.egg/corpustools/converter.py", line 211, in write_complete
    complete = self.make_complete()
  File "/usr/lib/python2.7/site-packages/CorpusTools-0.7.8-py2.7.egg/corpustools/converter.py", line 196, in make_complete
    self.validate_complete(complete)
  File "/usr/lib/python2.7/site-packages/CorpusTools-0.7.8-py2.7.egg/corpustools/converter.py", line 111, in validate_complete
    dtd = etree.DTD(os.path.join(os.getenv('GTHOME'), 'gt/dtd/corpus.dtd'))
  File "dtd.pxi", line 294, in lxml.etree.DTD.__init__ (src/lxml/lxml.etree.c:164400)
lxml.etree.DTDParseError: error parsing DTD
diedut>

**Comment by albbas** [comment]
## Comment 10034
Date: 2015-01-29 12:52:50 +0100
From: @leneantonsen

(In reply to comment #2)
> Eg konverterer no science-korpus på gtlab, og får eit anna resultat enn Lene.

Presisering: jeg har kun sett på filene i converted, jeg har ikke konvertert sjøl.

**Comment by albbas** [comment]
## Comment 10041
Date: 2015-01-31 15:55:37 +0100
From: @Trondtr

Eg konverterer no på Mac, med siste CorpusTools, og får desse resultata:

SDÁ: 2006-årgangen er konvertert feil (ein bokstav på kvar linje), men dei andre ser fin ut. Ser eg på pdf-en er det eit bliete der.
sust/sust253..: Her er dei samiske bokstavane koda utanfor Unicode, eg får ikkje opp talverdiar for dei i det heile.
diedut2007: Her får eg mellomrom for desse samiske teikna.

Konklusjonen på dette er for meg at vi fjernar sda2006 , diedut2007 og sust253 frå korpuset (eller merkar dei med "ikkje konverter"). Den dagen vi er ajour med andre delar av korpusinnsamlinga kan vi evt. skanne desse sjølv, og vi kan melde i frå at dei er feil.

**Comment by albbas** [comment]
## Comment 10042
Date: 2015-01-31 18:31:15 +0100
From: @leneantonsen

> Konklusjonen på dette er for meg at vi fjernar sda2006 , diedut2007 og sust253
> frå korpuset (eller merkar dei med "ikkje konverter"). Den dagen vi er ajour
> med andre delar av korpusinnsamlinga kan vi evt. skanne desse sjølv, og vi kan
> melde i frå at dei er feil.

Her er en av SDA 2006-artiklene: http://site.uit.no/aigecala/files/2013/03/2006-ylikoski.pdf
Bare ordene som er skrevet med kursiv, er søkbare, og det er de ordene som er lesbare i konverterbare. Jeg skal skrive mail om dette til redaksjonen, kanskje de skanner på nytt.

**Comment by albbas** [comment]
## Comment 10043
Date: 2015-01-31 18:47:54 +0100
From: @leneantonsen

> Her er en av SDA 2006-artiklene:
> http://site.uit.no/aigecala/files/2013/03/2006-ylikoski.pdf
> Bare ordene som er skrevet med kursiv, er søkbare, og det er de ordene som er
> lesbare i konverterbare. Jeg skal skrive mail om dette til redaksjonen, kanskje
> de skanner på nytt.

Sendte epost til SDA-redaksjonen i dag.

**Comment by albbas** [comment]
## Comment 10044
Date: 2015-01-31 19:19:58 +0100
From: @leneantonsen

> Sendte epost til SDA-redaksjonen i dag.
Det kom ny pdf-fil med alle artiklene i samme fil. Den er nå sendt til Ciprian. Jeg regner med at han har program for å kutte fila opp i artikler?

**Comment by albbas** [comment]
## Comment 10050
Date: 2015-02-02 15:35:37 +0100
From: @albbas

(In reply to comment #9)
> (In reply to comment #8)
> > (In reply to comment #0)
> > > Feil konvertering av nordsamisk bokstaver i science-korpus:
> > > 
> > > đ > ÿ
> > > č > þ
> > > ŋ > ƾ
> > > 
> > > 
> > 
> > i disse: 
> > 
> > allaskuvla/publications/diedut/Diedut_2007_3_bokblokka.pdf.xml
> > allaskuvla/publications/diedut/diedut_2009_1_samlet_20091015.pdf.xml
> > sust/sust253_ijas.pdf.xml
> 
> Jeg regner med at disse burde være mulige å konvertere riktig, siden de er 1:1
> ? Eller skal vi be om nye dokumenter?

Om det bare er i disse tre dokumentene slike feil oppstår, er det aller enkleste å skrive en erstatningsregel i metadatafila.

Eksempelvis for diedut_2009_1_samlet_20091015.pdf.xsl:
Fjern kommentartegnene på linje 128 og 153.

Erstatt disse to linjene:

            <xsl:with-param name="target" select="'str1/str2/str3/'"/>
            <xsl:with-param name="replacement" select="'rpl1/rpl2/rpl3/'"/>

med:

            <xsl:with-param name="target" select="'ÿ/þ/ƾ/'"/>
            <xsl:with-param name="replacement" select="'đ/č/ŋ/'"/>
